### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct

image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false # choices: [true, false]
freeze_multi_modal_projector: false # choices: [true, false]
freeze_language_model: false # choices: [true, false]
# Tắt deepspeed cho local training với RTX 3070 (8GB VRAM)
# deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
# Bạn cần giải nén đầy đủ thư mục data/ trước khi sử dụng.
dataset_dir: ../../data
# Danh sách dataset khớp với các file prompt hiện có trong data/
dataset: crohme_2014, crohme_2016, crohme_2019, crohme2023_test, crohme2023_val, hme100k_test, im2latexv2_test, im2latexv2_valid, mathwriting_test, mathwriting_val, mne_n1, mne_n2, mne_n3

# Nếu bạn tải thêm các biến thể dataset khác (ví dụ *_normalized) hãy thêm tên dataset tương ứng vào dòng trên.

template: qwen2_vl
cutoff_len: 2048
max_samples: 20000000
overwrite_cache: true
# Giảm số workers cho máy local
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: saves/qwen2.5_vl-3b/full/sft/standred/uni-mumer_local
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard

### train
# Giảm batch size cho RTX 3070 (8GB VRAM)
per_device_train_batch_size: 1
# Tăng gradient accumulation để giữ effective batch size
gradient_accumulation_steps: 16  # effective batch size = 1 * 16 = 16

learning_rate: 1.0e-5
# Train vài epoch trên local
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
save_only_model: true
resume_from_checkpoint: null

# no need to eval during training
### eval
# eval_dataset: crohme_2014,crohme_2016,crohme_2019
# val_size: 0
# per_device_eval_batch_size: 8
# eval_strategy: steps
# eval_steps: 1000

