### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct

# TỐI ƯU TỐC ĐỘ: Giảm image_max_pixels để tăng tốc độ xử lý (vẫn đủ chất lượng)
image_max_pixels: 32768  # Giảm từ 65536 để tăng tốc độ, vẫn đủ để nhận diện công thức toán
video_max_pixels: 16384
trust_remote_code: true
# Tối ưu memory khi load model
low_cpu_mem_usage: true

### method
stage: sft
do_train: true
# Sử dụng LoRA thay vì full fine-tuning để tiết kiệm memory
finetuning_type: lora
# LoRA settings - chỉ train adapter layers (tiết kiệm memory rất nhiều)
lora_target: all  # Train trên tất cả các layer có thể
lora_rank: 16  # Rank của LoRA (càng cao càng nhiều tham số, nhưng tốt hơn)
lora_alpha: 32  # Scaling factor (thường = 2 * rank)
lora_dropout: 0.05  # Dropout để tránh overfitting
# Quantization 4-bit để giảm memory khi load model (QUAN TRỌNG cho GPU 8GB!)
quantization_bit: 4
quantization_method: bnb
double_quantization: true  # Tiết kiệm thêm memory
# Không cần freeze với LoRA vì chỉ train adapter
freeze_vision_tower: false
freeze_multi_modal_projector: false
freeze_language_model: false
# Tắt deepspeed cho local training với RTX 3070 (8GB VRAM)
# deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
# Bạn cần giải nén đầy đủ thư mục data/ trước khi sử dụng.
dataset_dir: ../../data
media_dir: ..
# TỐI ƯU: Chỉ train với CROHME 2014 (986 samples) để đạt 100 epoch trong 8 giờ
# Với 986 samples, batch_size=2, grad_accum=8: ~62 steps/epoch
# 100 epochs = 6,200 steps → cần ~4.6 giây/step (khả thi với quantization)
dataset: crohme_2014

template: qwen2_vl
cutoff_len: 2048
max_samples: 20000000
overwrite_cache: true
# TỐI ƯU: Giảm workers để giảm overhead và tăng tốc độ
preprocessing_num_workers: 2  # Giảm từ 4 xuống 2
dataloader_num_workers: 1  # Giảm từ 2 xuống 1

### output
output_dir: saves/qwen2.5_vl-3b/lora/sft/standred/uni-mumer_crohme_100epoch
logging_steps: 10
save_steps: 200  # Giảm từ 500 xuống 200 để save thường xuyên hơn (mỗi ~3.2 epoch)
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard

### train
# TỐI ƯU: Tăng batch size lên 2 (với quantization 4-bit có thể làm được)
# Giảm gradient accumulation để tăng tốc độ
per_device_train_batch_size: 2  # Tăng từ 1 lên 2 (với quantization vẫn an toàn)
gradient_accumulation_steps: 8  # Giảm từ 16 xuống 8 (effective batch = 2 * 8 = 16, vẫn giữ chất lượng)
# Bật gradient checkpointing để tiết kiệm memory
gradient_checkpointing: true

# LoRA thường dùng learning rate cao hơn full fine-tuning
learning_rate: 5.0e-4  # Giữ nguyên cho LoRA
# TỐI ƯU: Train 100 epoch trong 8 giờ
# Với 986 samples, batch_size=2, grad_accum=8: ~62 steps/epoch
# 100 epochs = 6,200 steps → cần ~4.6 giây/step (khả thi!)
num_train_epochs: 100.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
save_only_model: true
resume_from_checkpoint: null
# Tối ưu memory
max_grad_norm: 1.0
optim: adamw_torch

# no need to eval during training
### eval
# eval_dataset: crohme_2014,crohme_2016,crohme_2019
# val_size: 0
# per_device_eval_batch_size: 8
# eval_strategy: steps
# eval_steps: 1000

