### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct

# Giảm image_max_pixels để đảm bảo đủ memory với quantization
image_max_pixels: 65536  # Giảm để an toàn với GPU 8GB
video_max_pixels: 16384
trust_remote_code: true
# Tối ưu memory khi load model
low_cpu_mem_usage: true

### method
stage: sft
do_train: true
# Sử dụng LoRA thay vì full fine-tuning để tiết kiệm memory
finetuning_type: lora
# LoRA settings - chỉ train adapter layers (tiết kiệm memory rất nhiều)
lora_target: all  # Train trên tất cả các layer có thể
lora_rank: 16  # Rank của LoRA (càng cao càng nhiều tham số, nhưng tốt hơn)
lora_alpha: 32  # Scaling factor (thường = 2 * rank)
lora_dropout: 0.05  # Dropout để tránh overfitting
# Quantization 4-bit để giảm memory khi load model (QUAN TRỌNG cho GPU 8GB!)
quantization_bit: 4
quantization_method: bnb
double_quantization: true  # Tiết kiệm thêm memory
# Không cần freeze với LoRA vì chỉ train adapter
freeze_vision_tower: false
freeze_multi_modal_projector: false
freeze_language_model: false
# Tắt deepspeed cho local training với RTX 3070 (8GB VRAM)
# deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
# Bạn cần giải nén đầy đủ thư mục data/ trước khi sử dụng.
dataset_dir: ../../data
media_dir: ..
# Danh sách dataset khớp với các file prompt hiện có trong data/
dataset: crohme_2014, crohme_2016, crohme_2019, crohme2023_test, crohme2023_val, hme100k_test, im2latexv2_test, im2latexv2_valid, mathwriting_test, mathwriting_val, mne_n1, mne_n2, mne_n3

# Nếu bạn tải thêm các biến thể dataset khác (ví dụ *_normalized) hãy thêm tên dataset tương ứng vào dòng trên.

template: qwen2_vl
cutoff_len: 2048
max_samples: 20000000
overwrite_cache: true
# Giảm số workers để tiết kiệm memory
preprocessing_num_workers: 4
dataloader_num_workers: 2

### output
output_dir: saves/qwen2.5_vl-3b/lora/sft/standred/uni-mumer_local
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard

### train
# Giữ batch size = 1 để đảm bảo đủ memory với quantization
per_device_train_batch_size: 1  # Giữ = 1 để an toàn
# Tăng gradient accumulation để giữ effective batch size
gradient_accumulation_steps: 16  # effective batch size = 1 * 16 = 16
# Bật gradient checkpointing để tiết kiệm memory
gradient_checkpointing: true

# LoRA thường dùng learning rate cao hơn full fine-tuning
learning_rate: 5.0e-4  # Tăng từ 1e-5 lên 5e-4 cho LoRA
# Train vài epoch trên local
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
save_only_model: true
resume_from_checkpoint: null
# Tối ưu memory
max_grad_norm: 1.0
optim: adamw_torch

# no need to eval during training
### eval
# eval_dataset: crohme_2014,crohme_2016,crohme_2019
# val_size: 0
# per_device_eval_batch_size: 8
# eval_strategy: steps
# eval_steps: 1000

